apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-store
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 80Gi
