apiVersion: v1
kind: ServiceAccount
metadata:
  name: skipper-aws-ingress
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: skipper-aws-ingress
rules:
- apiGroups: ["extensions"]
  resources: ["ingresses", "ingresses/status"]
  verbs: ["get", "list", "patch"]
- apiGroups: [""]
  resources: ["namespaces", "services", "endpoints"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: skipper-aws-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skipper-aws-ingress
subjects:
- kind: ServiceAccount
  name: skipper-aws-ingress
  namespace: kube-system
