apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    application: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: jenkins
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 2000
      containers:
      - name: jenkins
        image: <IMAGE_NAME>
        env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080

          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/run/docker.sock
          name: docker-socket
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-store
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
status: {}
