apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  labels:
    io.kompose.service: jenkins
    application: jenkins
spec:
  backend:
    serviceName: jenkins
    servicePort: 80
  rules:
  - host: ci.<DOMAIN>
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 80
